### ISSUE TITLE
CVE

### ISSUE THREAD

**Issue by odedimgn** [ruby-grape/mustermann-grape#15]
The Gemfile.lock includes rest-client in a vulnerable version, can you guys please bump this?

https://security.snyk.io/vuln/SNYK-RUBY-RESTCLIENT-20211

Thanks

**Comment by dblock** [comment]
Can you please contribute @odedimgn ?

**Comment by odedimgn** [comment]
I believe you just need to drop the lock file, not sure why its there

**Comment by dblock** [comment]
> I believe you just need to drop the lock file, not sure why its there

Go for it.

**Comment by dblock** [comment]
The .lock file can also be deleted since it's just to run CI with stable dependencies. Either way we need to get CI working again, I propose replacing Travis with GHA.
<img width="1240" alt="Screen Shot 2022-04-06 at 10 30 00 PM" src="https://user-images.githubusercontent.com/542335/162108499-da24a606-6b21-4654-8360-4eb37ff9dafa.png">
